# Generated by Django 5.2.8 on 2025-11-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学习日期')),
                ('hours_completed', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='完成学时')),
                ('attendance_status', models.CharField(choices=[('present', '出席'), ('absent', '缺席'), ('late', '迟到'), ('excused', '请假')], default='present', max_length=10, verbose_name='出勤状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学时记录',
                'verbose_name_plural': '学时记录',
                'db_table': 'training_studyhour',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_required', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总需学时')),
                ('hours_completed', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='已完成学时')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='完成百分比')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='最后学习日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培训进度',
                'verbose_name_plural': '培训进度',
                'db_table': 'training_trainingprogress',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('status', models.CharField(choices=[('enrolled', '已选课'), ('completed', '已完成'), ('dropped', '已退课')], default='enrolled', max_length=10, verbose_name='状态')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最终成绩')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseschedule', verbose_name='课程安排')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'db_table': 'training_enrollment',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('homework', '作业'), ('quiz', '测验'), ('exam', '考试'), ('final', '期末')], max_length=10, verbose_name='成绩类型')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='满分')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='权重')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='training.enrollment', verbose_name='选课记录')),
            ],
            options={
                'verbose_name': '成绩记录',
                'verbose_name_plural': '成绩记录',
                'db_table': 'training_grade',
                'ordering': ['-graded_at'],
            },
        ),
    ]
