# Generated by Django 5.2.8 on 2025-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='院系')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='年级')),
                ('enrollment_date', models.DateField(verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('status', models.CharField(choices=[('active', '在读'), ('graduated', '已毕业'), ('suspended', '休学'), ('dropped', '退学')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'students_student',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('academic', '学术成就'), ('sports', '体育成就'), ('art', '艺术成就'), ('other', '其他成就')], max_length=10, verbose_name='成就类型')),
                ('title', models.CharField(max_length=200, verbose_name='成就标题')),
                ('description', models.TextField(blank=True, verbose_name='成就描述')),
                ('date_achieved', models.DateField(verbose_name='获得日期')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='student_achievements/', verbose_name='证书文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学员成就',
                'verbose_name_plural': '学员成就',
                'db_table': 'students_studentachievement',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话')),
                ('address', models.TextField(blank=True, verbose_name='联系地址')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='家长姓名')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='家长电话')),
            ],
            options={
                'verbose_name': '学员联系信息',
                'verbose_name_plural': '学员联系信息',
                'db_table': 'students_studentcontact',
            },
        ),
    ]
