# Generated by Django 5.2.8 on 2025-12-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student_photos/%Y/%m/%d/', verbose_name='相片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='相片描述')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为主相片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '学员相片',
                'verbose_name_plural': '学员相片',
                'db_table': 'students_studentphoto',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
