# Generated by Django 5.2.8 on 2025-11-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True, verbose_name='课程代码')),
                ('course_name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='课程类别')),
                ('total_hours', models.IntegerField(verbose_name='总学时')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='学分')),
                ('difficulty_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=15, verbose_name='难度级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='上课日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='教室')),
                ('max_students', models.IntegerField(default=30, verbose_name='最大学生数')),
                ('current_students', models.IntegerField(default=0, verbose_name='当前学生数')),
                ('status', models.CharField(choices=[('scheduled', '已安排'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=15, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程安排',
                'verbose_name_plural': '课程安排',
                'db_table': 'courses_courseschedule',
                'ordering': ['schedule_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('description', models.TextField(blank=True, verbose_name='资料描述')),
                ('file', models.FileField(upload_to='course_materials/', verbose_name='资料文件')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
                'db_table': 'courses_coursematerial',
                'ordering': ['-created_at'],
            },
        ),
    ]
