# Generated by Django 5.2.8 on 2025-11-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='teachers.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='teachers.teacher', verbose_name='教师'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherrating',
            unique_together={('teacher', 'student')},
        ),
    ]
